# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='posted_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default=1, max_length=255, verbose_name='Kurs'),
            preserve_default=False,
        ),
    ]
