# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170526_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, verbose_name='Czas')),
                ('min', models.CharField(max_length=255, verbose_name='Kurs minimalny')),
                ('max', models.CharField(max_length=255, verbose_name='Kurs maxymalny')),
            ],
        ),
    ]
