# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_cuurent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuurent',
        ),
    ]
